name: uni_quitter
description: Calculate your GPA and Grades
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: JetBrainsMono
      fonts:
      - asset: fonts/JetBrainsMono/fonts/ttf/JetBrainsMono-Regular.ttf

flutter_icons:
  ios: true
  image_path: "assets/logo.png"

